services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: "api-gateway"
    depends_on:
      - chat-service-container
      - user-service-container
    ports:
      - "8080:8080"
    environment:
      CHAT_SERVICE_URL: http://chat-service-container:8101
      USER_SERVICE_URL: http://user-service-container:8103
    networks:
      - shared-network

  chat-service-db:
    image: mongo:latest
    container_name: "chat-service-mongodb"
    ports:
      - "27017:27017"
    volumes:
      - ./chat-service/mongo-data:/data/db
    networks:
      - chat-network

  minio-storage:
    image: quay.io/minio/minio:latest
    container_name: "minio-storage"
    ports:
      - "9007:9000"
      - "9008:9008"
    env_file:
      - ./.env.global
    command: server /data --console-address ":9008"
    volumes:
      - ./minio-data:/data
    networks:
      - shared-network

  chat-service-container:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    image: chat-service:latest
    container_name: "chat-service-container"
    ports:
      - "8101:8101"
    depends_on:
      - chat-service-db
      - minio-storage
    networks:
      - chat-network
      - shared-network
    env_file:
      - ./.env.global
      - ./chat-service/.env
    environment:
     MINIO_BUCKET_PATH: chat-service

  user-service-container:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: "user-service-container"
    ports:
      - "8103:8103"
    depends_on:
      - minio-storage
    networks:
      - user-network
      - shared-network
    env_file:
      - ./.env.global
      - ./user-service/.env
    environment:
      MINIO_BUCKET_PATH: user-service

networks:
  chat-network:
    driver: bridge
  user-network:
    driver: bridge
  shared-network:
    driver: bridge
