server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chat-service-chats
          uri: http://localhost:8101
          predicates:
            - Path=/chats/**

        - id: chat-service-messages
          uri: http://localhost:8101
          predicates:
            - Path=/messages/**

        - id: chat-service-chat-members
          uri: http://localhost:8101
          predicates:
            - Path=/chat-members/**

        - id: user-service
          uri: http://localhost:8103
          predicates:
            - Path=/users/**

