server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowed-headers: "*"
            allow-credentials: true

      routes:
        - id: chat-service
          uri: ${CHAT_SERVICE_URL}
          predicates:
            - Path=/chats/**,/messages/**,/chat-members/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/user/**,/auth/**

        - id: relationship-service
          uri: ${RELATIONSHIP_SERVICE_URL}
          predicates:
            - Path=/relationship/**

        - id: post-service
          uri: ${POST_SERVICE_URL}
          predicates:
            - Path=/posts/**,/post_media/**,/post_viewer/**

        - id: comment-service'
          uri: ${COMMENT_SERVICE_URL}
          predicates:
            - Path=/comments/**,/comment_reaction/**