server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chat-service-chats
          uri: ${CHAT_SERVICE_URL}
          predicates:
            - Path=/chats/**

        - id: chat-service-messages
          uri: ${CHAT_SERVICE_URL}
          predicates:
            - Path=/messages/**

        - id: chat-service-chat-members
          uri: ${CHAT_SERVICE_URL}
          predicates:
            - Path=/chat-members/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/user/**

        - id: user-service-auth
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**